import { useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { HeartPulse, MapPin, MessageSquare, Phone, User, X } from 'lucide-react';

function SOSModal({ isOpen, onClose, userProfile }) {
  const [location, setLocation] = useState('Location permission is required for SOS.');
  const [mapsLink, setMapsLink] = useState('');
  const [locationLoading, setLocationLoading] = useState(false);
  const requestLocation = () => { if (!navigator.geolocation) { setLocation('Geolocation is not supported by this browser.'); return; } setLocationLoading(true); setLocation('Requesting location permission...'); navigator.geolocation.getCurrentPosition(({ coords }) => { const coordinates = `${coords.latitude.toFixed(6)}, ${coords.longitude.toFixed(6)}`; setLocation(coordinates); setMapsLink(`https://www.google.com/maps/search/?api=1&query=${coords.latitude},${coords.longitude}`); setLocationLoading(false); }, error => { setLocation(error.code === error.PERMISSION_DENIED ? 'Location access was denied. Allow location permission to share your position.' : 'Unable to fetch your location. Try again or enter it manually.'); setLocationLoading(false); }, { enableHighAccuracy: true, timeout: 10000, maximumAge: 30000 }); };
  useEffect(() => { if (isOpen) { setMapsLink(''); requestLocation(); } }, [isOpen]);
  if (!isOpen) return null;
  const contacts = userProfile?.contacts?.filter(Boolean) || [];
  const message = encodeURIComponent(`EMERGENCY ALERT! ${userProfile?.name || 'I am'} is having a severe allergic reaction to ${userProfile?.allergens?.join(', ') || 'unknown allergens'}. Location: ${mapsLink || location}`);
  return createPortal(<div className="modal-backdrop"><div className="modal-panel"><div className="bg-red-600 p-7 text-white text-center"><HeartPulse className="w-16 h-16 mx-auto mb-3 animate-pulse" /><h2 className="text-3xl font-black uppercase">Emergency SOS</h2><p className="text-red-100 mt-1">Immediate medical assistance required</p></div><div className="p-6 space-y-5"><div className="grid md:grid-cols-2 gap-4"><div className="info-box danger"><h3><User className="w-5 h-5" /> Patient</h3><p><b>Name:</b> {userProfile?.name || 'Unknown'}</p><p><b>Allergies:</b> {userProfile?.allergens?.join(', ') || 'None specified'}</p></div><div className="info-box"><h3><MapPin className="w-5 h-5" /> Location</h3>{mapsLink ? <a href={mapsLink} target="_blank" rel="noreferrer" className="text-blue-600 break-all">{location}</a> : <input className="field" value={location} onChange={event => setLocation(event.target.value)} />}{!mapsLink && <button type="button" onClick={requestLocation} disabled={locationLoading} className="primary-button mt-3 w-full justify-center">{locationLoading ? 'Requesting...' : 'Allow location access'}</button>}</div></div>{contacts.length ? <div className="space-y-3">{contacts.map((contact, index) => <div key={`${contact.phone}-${index}`} className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><div className="text-sm font-semibold text-slate-700">{contact.name || 'Emergency Contact'} · {contact.relation || 'Contact'}</div><div className="mt-2 grid grid-cols-1 sm:grid-cols-3 gap-2"><a href={`tel:${contact.phone}`} className="action-button bg-red-600"><Phone /> Call</a><a href={`sms:${contact.phone}?body=${message}`} className="action-button bg-slate-800"><MessageSquare /> SMS</a><a href={`https://wa.me/${contact.phone.replace(/[^0-9]/g, '')}?text=${message}`} target="_blank" rel="noreferrer" className="action-button bg-emerald-600"><MessageSquare /> WhatsApp</a></div></div>)}</div> : <div className="p-4 bg-slate-100 rounded-xl text-slate-500 text-center">No emergency contact configured.</div> } </div><button onClick={onClose} className="secondary-button m-5 mt-0 w-[calc(100%-2.5rem)]"><X className="w-5 h-5" /> Dismiss SOS</button></div></div>, document.body);
}

export function SOSButton({ userProfile }) {
  const [holding, setHolding] = useState(false); const [open, setOpen] = useState(false); const timer = useRef();
  const start = useCallback(() => { setHolding(true); timer.current = window.setTimeout(() => { setOpen(true); setHolding(false); }, 3000); }, []);
  const stop = useCallback(() => { setHolding(false); window.clearTimeout(timer.current); }, []);
  return <><button onMouseDown={start} onMouseUp={stop} onMouseLeave={stop} onTouchStart={start} onTouchEnd={stop} className={`sos-button ${holding ? 'sos-holding' : ''}`}><HeartPulse className="w-5 h-5" /> Hold 3s for SOS</button><SOSModal isOpen={open} onClose={() => setOpen(false)} userProfile={userProfile} /></>;
}
